# Generated by Django 5.0.6 on 2026-07-02 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_url', models.URLField(max_length=2000)),
                ('final_url', models.URLField(blank=True, max_length=2000)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('page_load_time_ms', models.IntegerField(blank=True, null=True)),
                ('html_size_kb', models.FloatField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2000)),
                ('robots_meta', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(blank=True, max_length=20)),
                ('charset', models.CharField(blank=True, max_length=50)),
                ('h1_count', models.IntegerField(default=0)),
                ('heading_structure', models.JSONField(blank=True, default=list)),
                ('word_count', models.IntegerField(default=0)),
                ('text_html_ratio', models.FloatField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('images_missing_alt', models.IntegerField(default=0)),
                ('internal_link_count', models.IntegerField(default=0)),
                ('external_link_count', models.IntegerField(default=0)),
                ('nofollow_link_count', models.IntegerField(default=0)),
                ('og_tags', models.JSONField(blank=True, default=dict)),
                ('twitter_tags', models.JSONField(blank=True, default=dict)),
                ('schema_types', models.JSONField(blank=True, default=list)),
                ('overall_score', models.IntegerField(default=0)),
                ('passed_count', models.IntegerField(default=0)),
                ('warning_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meta', 'Meta Tags'), ('content', 'Content'), ('technical', 'Technical'), ('images', 'Images'), ('links', 'Links'), ('social', 'Social'), ('structured_data', 'Structured Data'), ('accessibility', 'Accessibility'), ('best_practices', 'Best Practices')], max_length=30)),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('fail', 'Fail')], max_length=10)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('current_value', models.CharField(blank=True, max_length=1000)),
                ('affected_element', models.CharField(blank=True, max_length=1000)),
                ('recommendation', models.TextField()),
                ('informational_only', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='audits.audit')),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
    ]
